import {useEffect, useState} from 'react';

const Calendar = ({schedule}) => {

    // this code was generated by AI
    const [cells, setCells] = useState([]);

    useEffect(() => {
        console.log(schedule.classes);
        const updatedCells = [];
        for (const course of schedule.classes) {
            for (let i = 0; i < course.courseDays.length; i++) {
               updatedCells.push({
                    day: course.courseDays[i],
                    time: course.startTime,
                    endTime: course.endTime,
                    courseCode: course.courseCode,
                    courseTitle: course.courseTitle
                });
            }
        }
        setCells(updatedCells);
    }, [schedule]);

    // this code was generated by AI and slightly modified
    const renderCell = (day, time) => {
        const cellData = cells.find(
            (cell) =>
                cell.day === day &&
                time >= cell.time &&
                time < cell.endTime
            );
        if (cellData) {
            return (
                <td key={day} data-time={time} data-day={day}  style={{ backgroundColor: 'red' }}>
                         <p><strong>{cellData.courseCode}</strong></p>
                         <span>{cellData.courseTitle}</span>
                </td>
                );
        }
        return  <td key={day}></td>;
    };

    // this code was generated by AI and slightly modified
    return (<div className="calendar">
              <table>
                  <thead>
                      <tr>
                          <th>Time</th>
                          <th>Monday</th>
                          <th>Tuesday</th>
                          <th>Wednesday</th>
                          <th>Thursday</th>
                          <th>Friday</th>
                      </tr>
                  </thead>
                  <tbody>
                      {['08:00:00', '08:15:00', '08:30:00', '08:45:00', '09:00:00', '09:15:00', '09:30:00', '09:45:00', '10:00:00', '10:15:00', '10:30:00', '10:45:00', '11:00:00', '11:15:00', '11:30:00', '11:45:00', '12:00:00', '12:15:00', '12:30:00', '12:45:00', '13:00:00', '13:15:00', '13:30:00', '13:45:00', '14:00:00', '14:15:00', '14:30:00', '14:45:00', '15:00:00', '15:15:00', '15:30:00', '15:45:00','16:00:00','16:15:00','16:30:00','16:45:00','17:00:00','17:15:00','17:30:00','17:45:00','18:00:00','18:15:00','18:30:00','18:45:00','19:00:00','19:15:00','19:30:00','19:45:00','20:00:00','20:15:00','20:30:00','20:45:00'].map((time) => (
                            <tr key={time}>
                                <td>{time.endsWith(':00:00') ? time : ''}</td>
                                {['M', 'T', 'W', 'R', 'F'].map((day) => (
                                    renderCell(day, time)
                                ))}
                            </tr>
                        ))}
                  </tbody>
              </table>
          </div>
         );
}

export default Calendar;