import React from 'react';
import ReactModal from 'react-modal';
import { useParams, useNavigate } from "react-router-dom";
import axios from 'axios';
import Calendar from './calendar';
import './calendar.css';

const Schedule = () => {
    const { scheduleId } = useParams();
    const [data, setData] = React.useState(null);
    const [schedule, setSchedule] = React.useState(null);
    const [selectedCourse, setSelectedCourse] = React.useState(null); // State for selected course
    const [isModalOpen, setIsModalOpen] = React.useState(false); // State for modal visibility
    const navigate = useNavigate();

    const handleCellClick = (course) => {
        setSelectedCourse(course);
        setIsModalOpen(true);
    };

    const closeModal = () => {
        setIsModalOpen(false);
        setSelectedCourse(null);
    };


    // This code was generated by AI and significantly modified
    const fetchScheduleData = async (scheduleId, setData, setSchedule) => {
        try {
            const response = await axios.get(`http://localhost:8080/api/schedule?id=${scheduleId}`);
            setData(response.data);
            setSchedule(response.data);
        } catch (error) {
            console.error("Error fetching schedule data:", error);
        }
    };

    // This code was generated by AI and slightly modified
    const handleRename = async () => {
        const newName = prompt("Enter a new name for the schedule:");
        if (newName) {
            try {
                await axios.put(`http://localhost:8080/api/schedule/rename?id=${scheduleId}&name=${encodeURIComponent(newName)}`);
                setData((prevData) => ({ ...prevData, name: newName }));
            } catch (error) {
                console.error("Error renaming schedule:", error);
            }
        }
    };

    const handleDelete = async () => {
        try {
            await axios.get(`http://localhost:8080/api/schedule/delete?id=${scheduleId}`);
            navigate("/home", { replace: true });
        } catch (error) {
            console.error("Error deleting schedule:", error);
        }
    };


    React.useEffect(() => {
        fetchScheduleData(scheduleId, setData, setSchedule);

    }, [scheduleId]);

    return (
        <div style={{ padding: '2rem', backgroundColor: 'white', minHeight: '100vh', color: 'black' }}>
            <div className="schedule-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
                    {/* This code was generated by AI */}
                    { data ? (
                        <>
                        <h1 style={{
                            fontSize: '3rem',
                            fontWeight: 'bold',
                            color: '#990000',
                            marginBottom: '0'
                        }}>
                            {data.name}
                        </h1>
                        <div style={{ display: 'flex', gap: '1rem' }}>
                            <button onClick={handleRename}
                                    style={{
                                        padding: '0.5rem 1rem',
                                        backgroundColor: '#dc3545',
                                        color: 'white',
                                        border: 'none',
                                        borderRadius: '5px',
                                        cursor: 'pointer',
                                        fontSize: '1rem'
                                    }}
                                    onMouseOver={(e) => e.target.style.backgroundColor = '#a71d2a'}
                                    onMouseOut={(e) => e.target.style.backgroundColor = '#dc3545'}
                            >
                                Rename Schedule
                            </button>
                            <button onClick={handleDelete}
                                    style={{
                                        padding: '0.5rem 1rem',
                                        backgroundColor: 'white',
                                        color: '#dc3545',
                                        border: '2px solid #dc3545',
                                        borderColor: '#dc3545',
                                        borderRadius: '5px',
                                        cursor: 'pointer',
                                        fontSize: '1rem'
                                    }}
                                    onMouseOver={(e) => e.target.style.backgroundColor = '#F0DEDF'}
                                    onMouseOut={(e) => e.target.style.backgroundColor = 'white'}
                            >
                                Delete Schedule
                            </button>
                        </div>
                        </>
                    ) : (<p> Loading... </p>)}
            </div>

           { schedule ? (
                <Calendar schedule={schedule} onCellClick={handleCellClick} />
               ) : <p> Loading... </p>}

           {/* This code was generated by AI and significantly modified*/}
           {isModalOpen && selectedCourse ? (
               <ReactModal       isOpen={isModalOpen}
                                 contentLabel="Example Modal"
                                 className="ReactModal__Content"
                                 overlayClassName="ReactModal__Overlay">
                       <h2>{selectedCourse.courseTitle}</h2>
                       <p><strong>Course Code:</strong> {selectedCourse.courseCode}</p>
                       <div><strong>Times:</strong> {formatTime(selectedCourse)}</div>
                       <br></br>
                       <p><strong>Instructor:</strong> {selectedCourse.professor.name}</p>
                       <p><strong>Occupancy:</strong> {selectedCourse.numRegistered}/{selectedCourse.numSeats}</p>

                       <button onClick={closeModal}>Close</button>
               </ReactModal>
           ) : null}
        </div>
    );
}

const formatTime = (course) => {
        const timeStrings = [];
        for (let i = 0; i < course.startTime.length; i++) {
            timeStrings[i] = (`${course.startTime[i]} - ${course.endTime[i]} ${course.courseDays[i]}`);
        }

        return (
            <div>
                {timeStrings.map((timeString, index) => (
                    <div key={index}>{timeString}</div>
                ))}
            </div>
        );
    }


export default Schedule;