import React from 'react';
import ReactModal from 'react-modal';
import { useParams, useNavigate } from "react-router-dom";
import axios from 'axios';
import Calendar from './calendar';
import './calendar.css';

const Schedule = () => {
    const { scheduleId } = useParams();
    const [data, setData] = React.useState(null);
    const [schedule, setSchedule] = React.useState(null);
    const [selectedCourse, setSelectedCourse] = React.useState(null); // State for selected course
    const [isModalOpen, setIsModalOpen] = React.useState(false); // State for modal visibility
    const navigate = useNavigate();

    const handleCellClick = (course) => {
        setSelectedCourse(course);
        setIsModalOpen(true);
    };

    const closeModal = () => {
        setIsModalOpen(false);
        setSelectedCourse(null);
    };


    // This code was generated by AI and significantly modified
    const fetchScheduleData = async (scheduleId, setData, setSchedule) => {
        try {
            const response = await axios.get(`http://localhost:8080/api/schedule?id=${scheduleId}`);
            setData(response.data);
            setSchedule(response.data);
        } catch (error) {
            console.error("Error fetching schedule data:", error);
        }
    };

    // This code was generated by AI and slightly modified
    const handleRename = async () => {
        const newName = prompt("Enter a new name for the schedule:");
        if (newName) {
            try {
                await axios.put(`http://localhost:8080/api/schedule/rename?id=${scheduleId}&name=${encodeURIComponent(newName)}`);
                setData((prevData) => ({ ...prevData, name: newName }));
            } catch (error) {
                console.error("Error renaming schedule:", error);
            }
        }
    };

    const handleDelete = async () => {
        try {
            await axios.get(`http://localhost:8080/api/schedule/delete?id=${scheduleId}`);
            navigate("/home", { replace: true });
        } catch (error) {
            console.error("Error deleting schedule:", error);
        }
    };

    // This code was generated by AI
    const handleDeleteCourse = async (courseId) => {
        try {
            await axios.delete(`http://localhost:8080/api/course/delete?scheduleid=${scheduleId}&&courseid=${courseId}`);
            setSchedule((prevSchedule) => ({
                ...prevSchedule,
                classes: prevSchedule.classes.filter((course) => course.id !== courseId),
            }));
        } catch (error) {
            console.error("Error deleting course:", error);
        }
    };


    React.useEffect(() => {
        fetchScheduleData(scheduleId, setData, setSchedule);

    }, [scheduleId]);

    //This code was generated by AI and slightly modified
    return (
        <div style={{ display: 'flex', minHeight: '100vh', backgroundColor: 'white', color: 'black' }}>
            {/* Sidebar */}
             <div style={{
                width: '20%',
                backgroundColor: '#f8f9fa',
                padding: '1rem',
                borderRight: '1px solid #ddd',
                overflowY: 'auto'
            }}>
                 <h2 style={{ fontSize: '1.5rem', color: '#990000', marginBottom: '1rem' }}>Courses</h2>
                 {schedule && schedule.classes ? (
                     <div style={{ listStyleType: 'none', padding: 0, position: 'relative' }}>
                         {schedule.classes.map((course, index) => (
                             <div key={index} style={{
                                 display: 'flex',
                                 position: 'relative',
                                 marginBottom: '1rem',
                                 padding: '0.5rem',
                                 backgroundColor: '#ffffff',
                                 border: '1px solid #ddd',
                                 borderRadius: '5px',
                                 cursor: 'pointer',
                                 transition: 'all 0.3s ease'
                             }}
                                 onMouseOver={(e) => e.target.style.backgroundColor = '#eaf2f8'}
                                 onMouseOut={(e) => e.target.style.backgroundColor = '#ffffff'}
                                 onClick={() => handleCellClick(course)}
                             >
                                 <div style={{ flex: 1 }}>
                                     <strong>{course.courseCode}</strong>
                                     <p style={{ margin: 0 }}>{course.courseTitle}</p>
                                 </div>
                                 <button
                                     onClick={(e) => {
                                            e.stopPropagation(); // Prevent triggering the parent card's click event
                                            handleDeleteCourse(course.id);
                                         }}
                                      style={removeButtonStyle}
                                     onMouseOver={(e) => e.target.style.backgroundColor = '#F0DEDF'}
                                     onMouseOut={(e) => e.target.style.backgroundColor = 'white'}
                                 >
                                     X
                                 </button>
                             </div>
                         ))}
                     </div>
                 ) : <p>Loading courses...</p>}
            </div>


            {/* Main Content */}
            <div style={{ padding: '2rem', flex: 1 }}>
                <div className="schedule-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
                    { data ? (
                        <>
                        <h1 style={{
                            fontSize: '3rem',
                            fontWeight: 'bold',
                            color: '#990000',
                            marginBottom: '0'
                        }}>
                            {data.name}
                        </h1>
                        <div style={{ display: 'flex', gap: '1rem' }}>
                            <button onClick={handleRename}
                                    style={{
                                        padding: '0.5rem 1rem',
                                        backgroundColor: '#dc3545',
                                        color: 'white',
                                        border: 'none',
                                        borderRadius: '5px',
                                        cursor: 'pointer',
                                        fontSize: '1rem'
                                    }}
                                    onMouseOver={(e) => e.target.style.backgroundColor = '#a71d2a'}
                                    onMouseOut={(e) => e.target.style.backgroundColor = '#dc3545'}
                            >
                                Rename Schedule
                            </button>
                            <button onClick={handleDelete}
                                    style={{
                                        padding: '0.5rem 1rem',
                                        backgroundColor: 'white',
                                        color: '#dc3545',
                                        border: '2px solid #dc3545',
                                        borderColor: '#dc3545',
                                        borderRadius: '5px',
                                        cursor: 'pointer',
                                        fontSize: '1rem'
                                    }}
                                    onMouseOver={(e) => e.target.style.backgroundColor = '#F0DEDF'}
                                    onMouseOut={(e) => e.target.style.backgroundColor = 'white'}
                            >
                                Delete Schedule
                            </button>
                        </div>
                        </>
                    ) : (<p> Loading... </p>)}
                </div>

               { schedule ? (
                    <Calendar schedule={schedule} onCellClick={handleCellClick} />
                   ) : <p> Loading... </p>}

               {isModalOpen && selectedCourse ? (
                   <ReactModal       isOpen={isModalOpen}
                                     contentLabel="Course Details"
                                     className="ReactModal__Content"
                                     overlayClassName="ReactModal__Overlay">
                           <h2>{selectedCourse.courseTitle}</h2>
                           <p><strong>Course Code:</strong> {selectedCourse.courseCode}</p>
                           <div><strong>Times:</strong> {formatTime(selectedCourse)}</div>
                           <br></br>
                           <p><strong>Instructor:</strong> {selectedCourse.professor.name}</p>
                           <p><strong>Occupancy:</strong> {selectedCourse.numRegistered}/{selectedCourse.numSeats}</p>

                           <button onClick={closeModal}>Close</button>
                   </ReactModal>
               ) : null}
            </div>
        </div>
    );
}

const formatTime = (course) => {
    const timeStrings = [];
    for (let i = 0; i < course.startTime.length; i++) {
        timeStrings[i] = (`${course.startTime[i]} - ${course.endTime[i]} ${course.courseDays[i]}`);
    }

    return (
        <div>
            {timeStrings.map((timeString, index) => (
                <div key={index}>{timeString}</div>
            ))}
        </div>
    );
}

const removeButtonStyle = {
  backgroundColor: 'transparent',
  color: '#990000',
  border: '1px solid #990000', // Add a border around the button
  fontSize: '1rem',
  cursor: 'pointer',
  borderRadius: '50%', // Make the button circular
  width: '15px', // Set width for the button
  height: '15px', // Set height for the button
  position: 'absolute', // Position the button within the course item
  top: '50%', // Position it in the top-right corner
  right: '8px',
  transform: 'translateY(-50%)', // Adjust for vertical centering
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
};


export default Schedule;
