import React from 'react';
import { useParams } from "react-router-dom";
import axios from 'axios';

const Schedule = () => {
    const { scheduleId } = useParams();

    // This code was generated by AI and significantly modified
    const fetchScheduleData = async () => {
        try {
            const response = await axios.get(`http://localhost:8080/api/schedule?id=${scheduleId}`);
            console.log(response.data);




        } catch (error) {
            console.error("Error fetching schedule data:", error);
        }
    };

    React.useEffect(() => {
        fetchScheduleData();
    }, [scheduleId]);

    return (
        <div>
           <h1>Schedule Page</h1>
           <p>This is the schedule page of schedule {scheduleId}</p>
        </div>
    );
}

export default Schedule;