package edu.gcc.comp350;

// Most of the individual methods in this class were generated by GitHub Copilot after getting started. They were then tweaked and bug fixed.

import org.json.JSONArray;
import org.json.JSONObject;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Random;

//
/**
 * DatabaseConnect class that connects to the database and injects SQL.
 */
public class DatabaseConnect {
    protected Connection conn;

    public DatabaseConnect() {
    }

    /**
     * Connects to the database.
     */
    public void connect() {
        var url = "jdbc:sqlite:Database/scrumbucketData.db";
        try {
            System.out.println("Connected to the database.");
            conn = DriverManager.getConnection(url);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        createProfessorsTableInDatabase();
    }

    /**
     * Disconnects from the database.
     */
    public void disconnect() {
        if (conn != null) {
            try {
                conn.close();
                System.out.println("Disconnected from the database.");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }

    /**
     * Injects SQL into the database.
     *
     * @param sql the SQL to inject
     */
    protected void injectSql(String sql) {
        try (var stmt = conn.createStatement()) {
            stmt.executeUpdate(sql);
            System.out.println("Record accessed successfully.");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Selects data from the database.
     *
     * @param columns the columns to select
     * @param table the table to select from
     * @return an ArrayList of Objects containing the selected data
     */
    public ArrayList<Object> select(String columns, String table) {
        String sql = "SELECT " + columns + " FROM " + table;
        ArrayList<Object> results = new ArrayList<>();
        try (var stmt = conn.createStatement();
             var rs = stmt.executeQuery(sql)) {
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            while (rs.next()) {
                for (int i = 1; i <= columnCount; i++) {
                    Object value = rs.getObject(i);
                    results.add(value);
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return results;
    }

    /**
     * Clears the database by dropping the Courses table.
     */
    protected void clearDatabase() {
        injectSql("DROP TABLE IF EXISTS Courses");
        injectSql("DROP TABLE IF EXISTS Student");
        injectSql("DROP TABLE IF EXISTS Schedule");
        injectSql("DROP TABLE IF EXISTS ScheduleCourses");
        injectSql("DROP TABLE IF EXISTS Professors");
        injectSql("DROP TABLE IF EXISTS StudentRatings");
    }

    protected void clearCoursesFromDatabase() {
        injectSql("DROP TABLE IF EXISTS Courses");
    }

    /**
     * Creates the database with a Courses table.
     */
    public void createDatabase() {
        // course table
        String sql = """
            CREATE TABLE IF NOT EXISTS Courses (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             courseTitle TEXT NOT NULL,
             professor TEXT NOT NULL,
             session TEXT NOT NULL,
             startTime TEXT NOT NULL,
             endTime TEXT NOT NULL,
             courseDays TEXT NOT NULL,
             courseDept TEXT NOT NULL,
             courseCode TEXT NOT NULL,
             numSeats INTEGER NOT NULL DEFAULT 2,
             numRegistered INTEGER NOT NULL DEFAULT 0
            );""";
        injectSql(sql);

        // student table
        sql = """
            CREATE TABLE IF NOT EXISTS Student (
             id INTEGER PRIMARY KEY,
             name TEXT NOT NULL,
             major TEXT NOT NULL,
             minor TEXT,
             username TEXT UNIQUE NOT NULL,
             password TEXT NOT NULL
            );""";
        injectSql(sql);

        // schedule table
        sql = """
            CREATE TABLE IF NOT EXISTS Schedule (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             scheduleTitle TEXT NOT NULL,
             student INTEGER,
             FOREIGN KEY (student) REFERENCES Student(id)
            );""";
        injectSql(sql);

        // schedule course table
        sql = """
            CREATE TABLE IF NOT EXISTS ScheduleCourses (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             schedule INTEGER,
             course INTEGER,
             FOREIGN KEY (schedule) REFERENCES Schedule(id),
             FOREIGN KEY (course) REFERENCES Courses(id)
            );""";
        injectSql(sql);

        // Professors table
        sql = """
             CREATE TABLE IF NOT EXISTS Professors (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             score INTEGER NOT NULL,
             professorName TEXT NOT NULL,
             department TEXT NOT NULL
             );""";
        injectSql(sql);
    }

    protected void createCoursesTableInDatabase() {
        // course table
        String sql = """
            CREATE TABLE IF NOT EXISTS Courses (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             courseTitle TEXT NOT NULL,
             professor TEXT NOT NULL,
             session TEXT NOT NULL,
             startTime TEXT NOT NULL,
             endTime TEXT NOT NULL,
             courseDays TEXT NOT NULL,
             courseDept TEXT NOT NULL,
             courseCode TEXT NOT NULL
             numSeats INTEGER NOT NULL DEFAULT 2,
             numRegistered INTEGER NOT NULL DEFAULT 0
            );""";
        injectSql(sql);
    }

    /**
     * Creates the Professors table if it does not already exist.
     */
    private void createProfessorsTableInDatabase() {
        String sql = """
         CREATE TABLE IF NOT EXISTS Professors (
         id INTEGER PRIMARY KEY AUTOINCREMENT,
         score INTEGER NOT NULL,
         professorName TEXT NOT NULL,
         department TEXT NOT NULL
         );""";
        injectSql(sql);
    }
//    /**
//     * If the database Courses table does not exist, reset it. Else, it already exists.
//     */
//    protected void setDatabase() {
//        String sql = "SELECT name FROM sqlite_master WHERE type='table' AND name='Courses'";
//        try (var stmt = conn.createStatement();
//             var rs = stmt.executeQuery(sql)) {
//            if (!rs.next()) {
//                resetCoursesInDatabase();
//            } else {
//                System.out.println("Database contains data.");
//            }
//        } catch (SQLException e) {
//            System.out.println(e.getMessage());
//        }
//    }

    public void setCoursesInDatabase() {
        String sql = "SELECT name FROM sqlite_master WHERE type='table' AND name='Courses'";
        try (var stmt = conn.createStatement();
             var rs = stmt.executeQuery(sql)) {
            if (!rs.next()) {
                resetCoursesInDatabase();
            } else {
                System.out.println("Database contains data.");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public void setProfessorsInDatabase() {
        String sql = "SELECT name FROM sqlite_master WHERE type='table' AND name='Professors'";
        try (var stmt = conn.createStatement();
             var rs = stmt.executeQuery(sql)) {
            if (!rs.next()) {
                resetProfessorsInDatabase();
            } else {
                System.out.println("Professors table already exists in the database.");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public void resetProfessorsInDatabase() {
        String sql = """
        CREATE TABLE IF NOT EXISTS Professors (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        score INTEGER NOT NULL,
        professorName TEXT NOT NULL,
        department TEXT NOT NULL
        );""";
        injectSql(sql);
        System.out.println("Professors table has been created/reset.");
    }


    /**
     * Resets the database by clearing it and repopulating it with course data.
     */
    protected void resetDatabase() {
        System.out.println("Resetting database.");
        clearDatabase();
        populateCoursesInDatabase();
        // populateStudentsInDatabase();
        // populateSchedulesInDatabase();
        populateProfessorsInDatabase();
    }

    public void resetCoursesInDatabase() {
        System.out.println("Resetting database.");
        clearCoursesFromDatabase();
        populateCoursesInDatabase();
    }

    /**
     * Populates the database with course data from a JSON file.
     */
    protected void populateCoursesInDatabase() {
        createCoursesTableInDatabase();
        String filePath = "Database/data_wolfe.json";
        try {
            String content = new String(Files.readAllBytes(Paths.get(filePath)));
            JSONObject jsonObject = new JSONObject(content);


            JSONArray coursesArray = jsonObject.getJSONArray("classes");
            String courseSql = "INSERT INTO Courses (courseTitle, professor, session, startTime, endTime, courseDays, courseDept, courseCode, numSeats, numRegistered) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement courseStmt = conn.prepareStatement(courseSql)) {
                for (int i = 0; i < coursesArray.length(); i++) {
                    JSONObject course = coursesArray.getJSONObject(i);
                    JSONArray timeData = course.getJSONArray("times");
                    StringBuilder day = new StringBuilder();
                    StringBuilder startTime = new StringBuilder();
                    StringBuilder endTime = new StringBuilder();
                    for (Object time : timeData) {
                        JSONObject timeObj = (JSONObject) time;
                        if (!day.isEmpty()) day.append(", ");
                        day.append(timeObj.getString("day"));
                        if (!startTime.isEmpty()) startTime.append(", ");
                        startTime.append(timeObj.getString("start_time"));
                        if (!endTime.isEmpty()) endTime.append(", ");
                        endTime.append(timeObj.getString("end_time"));
                    }

                    courseStmt.setString(1, course.getString("name"));
                    courseStmt.setString(2, course.getJSONArray("faculty").toString());
                    courseStmt.setString(3, course.getString("semester"));
                    courseStmt.setString(4, startTime.toString());
                    courseStmt.setString(5, endTime.toString());
                    courseStmt.setString(6, day.toString()); // Use the accumulated days
                    courseStmt.setString(7, course.getString("subject"));
                    courseStmt.setString(8, course.getString("subject") + " " + course.getInt("number") + " " + course.getString("section"));
                    courseStmt.setInt(9, 2);
                    courseStmt.setInt(10, 0);
                    courseStmt.executeUpdate();
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading JSON file: " + e.getMessage());
        } catch (Exception e) {
            System.err.println("Error parsing JSON data: " + e.getMessage());
        }
    }


    public void populateProfessorsInDatabase() {
        createProfessorsTableInDatabase();
        String filePath = "Database/data_wolfe.json";
        Random random = new Random(); // Random number generator

        try {
            String content = new String(Files.readAllBytes(Paths.get(filePath)));
            JSONObject jsonObject = new JSONObject(content);
            JSONArray classesArray = jsonObject.getJSONArray("classes");

            String insertSql = "INSERT INTO Professors (professorName, department, score) VALUES (?, ?, ?)";

            Set<String> seenProfessors = new HashSet<>(); // To avoid duplicate entries
            try (PreparedStatement stmt = conn.prepareStatement(insertSql)) {
                for (int i = 0; i < classesArray.length(); i++) {
                    JSONObject course = classesArray.getJSONObject(i);
                    JSONArray facultyArray = course.getJSONArray("faculty");

                    for (int j = 0; j < facultyArray.length(); j++) {
                        String professorName = facultyArray.getString(j);
                        String department = course.getString("subject");

                        // Check if this professor already exists in the database
                        String checkSql = "SELECT COUNT(*) FROM Professors WHERE professorName = ? AND department = ?";
                        try (PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {
                            checkStmt.setString(1, professorName);
                            checkStmt.setString(2, department);
                            ResultSet rs = checkStmt.executeQuery();
                            if (rs.next() && rs.getInt(1) == 0) {
                                // Insert professor if not already present
                                int randomScore = random.nextInt(5) + 1; // Random score from 1 to 5
                                stmt.setString(1, professorName);
                                stmt.setString(2, department);
                                stmt.setInt(3, randomScore);
                                stmt.executeUpdate();
                            }
                        }
                    }
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading JSON file: " + e.getMessage());
        } catch (Exception e) {
            System.err.println("Error parsing JSON data: " + e.getMessage());
        }
    }




    public List<Professor> getAllProfessors() {
        List<Professor> professors = new ArrayList<>();
        String sql = "SELECT * FROM Professors"; // SQL to retrieve all professors
        try (var stmt = conn.createStatement();
             var rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                int id = rs.getInt("id");
                int score = rs.getInt("score");
                String name = rs.getString("professorName");
                String department = rs.getString("department");
                professors.add(new Professor(id, score, name, department));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return professors;
    }

    /**
     * Rates a professor by a student.
     *
     * @param studentId   the ID of the current user
     * @param professorId the ID of the professor
     * @param newRating   the new rating to be given
     * @return true if the rating was successful, false otherwise
     */
    public boolean rateProfessor(int studentId, int professorId, double newRating) {
        try {
            // Check if the student already rated this professor
            String checkSql = "SELECT COUNT(*) FROM StudentRatings WHERE studentId = ? AND professorId = ?";
            try (PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {
                checkStmt.setInt(1, studentId);
                checkStmt.setInt(2, professorId);
                ResultSet rs = checkStmt.executeQuery();
                if (rs.next() && rs.getInt(1) > 0) {
                    System.out.println("Student has already rated this professor.");
                    return false;
                }
            }

            String getProfSql = "SELECT score, numRatings FROM Professors WHERE id = ?";
            int numRatings = 0;
            double oldAvg = 0;
            try (PreparedStatement getStmt = conn.prepareStatement(getProfSql)) {
                getStmt.setInt(1, professorId);
                ResultSet rs = getStmt.executeQuery();
                if (rs.next()) {
                    oldAvg = rs.getDouble("score");
                    numRatings = rs.getInt("numRatings");
                }
            }

            double newAvg = Math.round(((oldAvg * numRatings) + newRating) / (numRatings + 1) * 100.0) / 100.0;

            String updateProfSql = "UPDATE Professors SET score = ?, numRatings = ? WHERE id = ?";
            try (PreparedStatement updateStmt = conn.prepareStatement(updateProfSql)) {
                updateStmt.setDouble(1, newAvg);
                updateStmt.setInt(2, numRatings + 1);
                updateStmt.setInt(3, professorId);
                updateStmt.executeUpdate();
            }

            String insertRatingSql = "INSERT INTO StudentRatings (studentId, professorId, rating) VALUES (?, ?, ?)";
            try (PreparedStatement insertStmt = conn.prepareStatement(insertRatingSql)) {
                insertStmt.setInt(1, studentId);
                insertStmt.setInt(2, professorId);
                insertStmt.setDouble(3, newRating);
                insertStmt.executeUpdate();
            }

            return true;
        } catch (SQLException e) {
            System.out.println("Error rating professor: " + e.getMessage());
            return false;
        }
    }

    //For creating the needed professor rating tables
    public void ProfRatings() {
        try {
            DatabaseMetaData meta = conn.getMetaData();
            ResultSet rs = meta.getColumns(null, null, "Professors", "numRatings");
            if (!rs.next()) {
                injectSql("ALTER TABLE Professors ADD COLUMN numRatings INTEGER DEFAULT 0;");
                System.out.println("Added numRatings column to Professors table.");
            }

            String checkSql = "SELECT name FROM sqlite_master WHERE type='table' AND name='StudentRatings'";
            try (var stmt = conn.createStatement(); ResultSet checkRs = stmt.executeQuery(checkSql)) {
                if (!checkRs.next()) {
                    injectSql("""
                    CREATE TABLE IF NOT EXISTS StudentRatings (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        studentId INTEGER NOT NULL,
                        professorId INTEGER NOT NULL,
                        rating REAL NOT NULL,
                        UNIQUE(studentId, professorId),
                        FOREIGN KEY (studentId) REFERENCES Student(id),
                        FOREIGN KEY (professorId) REFERENCES Professors(id)
                    );
                """);
                    System.out.println("Created StudentRatings table.");
                }
            }
        } catch (SQLException e) {
            System.err.println("Error ensuring rating schema: " + e.getMessage());
        }
    }
}