package edu.gcc.comp350;

// Most of the individual methods in this class were generated by GitHub Copilot after getting started. They were then tweaked and bug fixed.

import org.json.JSONArray;
import org.json.JSONObject;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.*;
import java.util.ArrayList;

/**
 * DatabaseConnect class that connects to the database and injects SQL.
 */
public class DatabaseConnect {
    protected Connection conn;

    protected DatabaseConnect() {
    }

    /**
     * Connects to the database.
     */
    protected void connect() {
        var url = "jdbc:sqlite:Database/scrumbucketData.db";
        try {
            System.out.println("Connected to the database.");
            conn = DriverManager.getConnection(url);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Disconnects from the database.
     */
    protected void disconnect() {
        if (conn != null) {
            try {
                conn.close();
                System.out.println("Disconnected from the database.");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }

    /**
     * Injects SQL into the database.
     *
     * @param sql the SQL to inject
     */
    protected void injectSql(String sql) {
        try (var stmt = conn.createStatement()) {
            stmt.executeUpdate(sql);
            System.out.println("Record accessed successfully.");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Selects data from the database.
     *
     * @param columns the columns to select
     * @param table the table to select from
     * @return an ArrayList of Objects containing the selected data
     */
    protected ArrayList<Object> select(String columns, String table) {
        String sql = "SELECT " + columns + " FROM " + table;
        ArrayList<Object> results = new ArrayList<>();
        try (var stmt = conn.createStatement();
             var rs = stmt.executeQuery(sql)) {
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            while (rs.next()) {
                for (int i = 1; i <= columnCount; i++) {
                    Object value = rs.getObject(i);
                    results.add(value);
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return results;
    }

    /**
     * Clears the database by dropping the Courses table.
     */
    protected void clearDatabase() {
        injectSql("DROP TABLE IF EXISTS Courses");
        injectSql("DROP TABLE IF EXISTS Student");
        injectSql("DROP TABLE IF EXISTS Schedule");
        injectSql("DROP TABLE IF EXISTS ScheduleCourses");
    }

    protected void clearCoursesFromDatabase() {
        injectSql("DROP TABLE IF EXISTS Courses");
    }

    /**
     * Creates the database with a Courses table.
     */
    protected void createDatabase() {
        // course table
        String sql = """
            CREATE TABLE IF NOT EXISTS Courses (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             courseTitle TEXT NOT NULL,
             professor TEXT NOT NULL,
             session TEXT NOT NULL,
             startTime TEXT NOT NULL,
             endTime TEXT NOT NULL,
             courseDays TEXT NOT NULL,
             courseDept TEXT NOT NULL,
             courseCode TEXT NOT NULL
            );""";
        injectSql(sql);

        // student table
        sql = """
            CREATE TABLE IF NOT EXISTS Student (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             courseTitle TEXT NOT NULL,
             major TEXT NOT NULL,
             minor TEXT
            );""";
        injectSql(sql);

        // schedule table
        sql = """
            CREATE TABLE IF NOT EXISTS Schedule (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             scheduleTitle TEXT NOT NULL,
             student INTEGER,
             FOREIGN KEY (student) REFERENCES Student(id)
            );""";
        injectSql(sql);

        // schedule course table
        sql = """
            CREATE TABLE IF NOT EXISTS ScheduleCourses (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             schedule INTEGER,
             FOREIGN KEY (schedule) REFERENCES Schedule(id),
             course INTEGER,
             FOREIGN KEY (course) REFERENCES Courses(id)
            );""";
        injectSql(sql);
    }

    protected void createCoursesTableInDatabase() {
        // course table
        String sql = """
            CREATE TABLE IF NOT EXISTS Courses (
             id INTEGER PRIMARY KEY AUTOINCREMENT,
             courseTitle TEXT NOT NULL,
             professor TEXT NOT NULL,
             session TEXT NOT NULL,
             startTime TEXT NOT NULL,
             endTime TEXT NOT NULL,
             courseDays TEXT NOT NULL,
             courseDept TEXT NOT NULL,
             courseCode TEXT NOT NULL
            );""";
        injectSql(sql);
    }
//    /**
//     * If the database Courses table does not exist, reset it. Else, it already exists.
//     */
//    protected void setDatabase() {
//        String sql = "SELECT name FROM sqlite_master WHERE type='table' AND name='Courses'";
//        try (var stmt = conn.createStatement();
//             var rs = stmt.executeQuery(sql)) {
//            if (!rs.next()) {
//                resetCoursesInDatabase();
//            } else {
//                System.out.println("Database contains data.");
//            }
//        } catch (SQLException e) {
//            System.out.println(e.getMessage());
//        }
//    }

    protected void setCoursesInDatabase() {
        String sql = "SELECT name FROM sqlite_master WHERE type='table' AND name='Courses'";
        try (var stmt = conn.createStatement();
             var rs = stmt.executeQuery(sql)) {
            if (!rs.next()) {
                resetCoursesInDatabase();
            } else {
                System.out.println("Database contains data.");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Resets the database by clearing it and repopulating it with course data.
     */
    protected void resetDatabase() {
        System.out.println("Resetting database.");
        clearDatabase();
        populateCoursesInDatabase();
        // populateStudentsInDatabase();
        // populateSchedulesInDatabase();
        // populateProfessorsInDatabase();
        // TODO: Add method to populate data within database
    }

    protected void resetCoursesInDatabase() {
        System.out.println("Resetting database.");
        clearCoursesFromDatabase();
        populateCoursesInDatabase();
    }

    /**
     * Populates the database with course data from a JSON file.
     */
    protected void populateCoursesInDatabase() {
        createCoursesTableInDatabase();
        String filePath = "Database/data_wolfe.json";
        try {
            String content = new String(Files.readAllBytes(Paths.get(filePath)));
            JSONObject jsonObject = new JSONObject(content);

            // TODO: Put times parsing here
            // Parsing and inserting courses
            JSONArray coursesArray = jsonObject.getJSONArray("classes");
            String courseSql = "INSERT INTO Courses (courseTitle, professor, session, startTime, endTime, courseDays, courseDept, courseCode) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement courseStmt = conn.prepareStatement(courseSql)) {
                for (int i = 0; i < coursesArray.length(); i++) {
                    JSONObject course = coursesArray.getJSONObject(i);
                    JSONArray timeData = course.getJSONArray("times");
                    StringBuilder day = new StringBuilder();
                    StringBuilder endTime = new StringBuilder();
                    StringBuilder startTime = new StringBuilder();
                    for (Object time : timeData) {
                        JSONObject timeObj = (JSONObject) time;
                        if (!day.isEmpty()) day.append(", ");
                        if (!endTime.isEmpty()) endTime.append(", ");
                        if (!startTime.isEmpty()) startTime.append(", ");
                        day.append(timeObj.getString("day"));
                        endTime.append(timeObj.getString("end_time"));
                        startTime.append(timeObj.getString("start_time"));
                    }
                    courseStmt.setString(1, course.getString("name"));
                    courseStmt.setString(2, course.getJSONArray("faculty").toString());
                    courseStmt.setString(3, course.getString("semester"));
                    courseStmt.setString(4, String.valueOf(startTime));
                    courseStmt.setString(5, String.valueOf(endTime));
                    courseStmt.setString(6, String.valueOf(day));
                    courseStmt.setString(7, course.getString("subject"));
                    courseStmt.setString(8, course.getString("subject")+" "+course.getInt("number")+" "+course.getString("section"));
                    courseStmt.executeUpdate();
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading JSON file: " + e.getMessage());
        } catch (Exception e) {
            System.err.println("Error parsing JSON data: " + e.getMessage());
        }
    }

}