package edu.gcc.comp350;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import static edu.gcc.comp350.Main.*;

public class Student {

    private int id;
    private String name;
    private String major;
    private List<String> minors;
    private List<Schedule> schedules;

    protected Student(int id, String name, String major, List<String> minors) {
        this.name = name;
        this.major = major;
        this.minors = minors;
        this.id = id;
        this.schedules = getSchedulesFromDatabase();
    }

    /**
     * This code was generated by AI and slightly modified
     * @return List<Schedule> a list of all schedules belonging to the current student
     */
    protected List<Schedule> getSchedulesFromDatabase() {
        List<Schedule> schedules = new ArrayList<>();
        String sql = "SELECT id, scheduleTitle FROM Schedule WHERE student = " + this.id;

        try (var stmt = Main.db.conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                int scheduleId = rs.getInt("id");
                String scheduleTitle = rs.getString("name");
                Schedule schedule = new Schedule(scheduleTitle, scheduleId);
                schedules.add(schedule);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        return schedules;
    }

    protected int getId() {
        return 1;
    }

    protected String getName() {
        return name;
    }

    protected void setName(String name) {
        this.name = name;
    }

    protected String getMajor() {
        return major;
    }

    protected List<String> getMinors() {
        return minors;
    }

    protected List<Schedule> getSchedules() {
        return schedules;
    }

    protected Schedule addSchedule(Schedule schedule) {
        schedules.add(schedule);
        return schedule;
    }

    protected void deleteSchedule(Schedule schedule) {
        schedules.remove(schedule);
        String scheduleSql = "DELETE FROM ScheduleCourses WHERE schedule = " + schedule.getId();
        db.injectSql(scheduleSql);
        scheduleSql = "DELETE FROM Schedule WHERE id = " + schedule.getId();
        db.injectSql(scheduleSql);
    }

    protected Schedule getSchedule(int id) {
        for (Schedule schedule : schedules) {
            if (schedule.getId() == id) {
                return schedule;
            }
        }
        System.out.println("Schedule not found");
        return null;
    }

    protected void saveSchedule(Schedule schedule) {
        deleteSchedule(schedule);
//        String scheduleSql = "INSERT INTO Schedule (scheduleTitle, student) VALUES ('" + schedule.getName() + "', " + id + ")";
//        db.injectSql(scheduleSql);

        try (var pstmt = db.conn.prepareStatement("INSERT INTO Schedule (scheduleTitle, student) VALUES (?, ?)")) {
            pstmt.setString(1, schedule.getName());
            pstmt.setInt(2, id);
            pstmt.executeUpdate();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        String scheduleCourseSql = "DELETE FROM ScheduleCourses WHERE schedule = " + schedule.getId();
        db.injectSql(scheduleCourseSql);

        for (Course course : schedule.getCourses()) {
            try (var pstmt = db.conn.prepareStatement("INSERT INTO ScheduleCourses (schedule, course) VALUES (?, ?)")) {
                pstmt.setInt(1, schedule.getId());
                pstmt.setInt(2, course.getID());
                pstmt.executeUpdate();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }
}
