package edu.gcc.comp350;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import static edu.gcc.comp350.RefactoredMain.*;

public class Student {

    private int id;
    private String name;
    private String major;
    private List<String> minors;
    private List<Schedule> schedules = new ArrayList<>();

    protected Student(String name, String major, List<String> minors) {
        this.name = name;
        this.major = major;
        this.minors = minors;

        // put this student in db
        try (var pstmt = db.conn.prepareStatement("INSERT INTO Student (name, major, minor, username, password) VALUES (?, ?, ?, ?, ?)")) {
            pstmt.setString(1, this.name);
            pstmt.setString(2, major);
            pstmt.setString(3, minors.toString());
            pstmt.setString(4, this.name);
            pstmt.setString(5, this.name);
            pstmt.executeUpdate();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        // get id assigned from db
        String sql = "SELECT id FROM Student WHERE name = '" + this.name + "'";

        try (var stmt = RefactoredMain.db.conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
                this.id = rs.getInt("id");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        this.schedules = getSchedulesFromDatabase();

    }


    protected Student(int id, String name, String major, List<String> minors) {
        this.name = name;
        this.major = major;
        this.minors = minors;
        this.id = id;

        schedules = getSchedulesFromDatabase();
    }

    /**
     * This code was generated by AI and slightly modified
     * @return List<Schedule> a list of all schedules belonging to the current student
     */
    protected List<Schedule> getSchedulesFromDatabase() {
        List<Schedule> schedules = new ArrayList<>();
        String sql = "SELECT id, scheduleTitle FROM Schedule WHERE student = " + this.id;

        try (var stmt = RefactoredMain.db.conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                int scheduleId = rs.getInt("id");
                String scheduleTitle = rs.getString("scheduleTitle");
                Schedule schedule = new Schedule(scheduleTitle, scheduleId);
                schedules.add(schedule);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        return schedules;
    }

    protected int getId() {
        return id;
    }

    protected String getName() {
        return name;
    }

    protected void setName(String name) {
        this.name = name;
    }

    protected String getMajor() {
        return major;
    }

    protected List<String> getMinors() {
        return minors;
    }

    protected List<Schedule> getSchedules() {
        return schedules;
    }

    protected Schedule addSchedule(Schedule schedule) {
        schedules.add(schedule);
        return schedule;
    }

    protected void deleteSchedule(Schedule schedule) {
        schedules.remove(schedule);
        String scheduleSql = "DELETE FROM ScheduleCourses WHERE schedule = " + schedule.getId();
        db.injectSql(scheduleSql);
        scheduleSql = "DELETE FROM Schedule WHERE id = " + schedule.getId();
        db.injectSql(scheduleSql);
    }

    public Schedule getSchedule(int index) {
        try {
            return schedules.get(index);
        } catch (IndexOutOfBoundsException e) {
            System.out.println("Schedule not found");
            return null;
        }
    }
    protected void saveSchedule(Schedule schedule) {
        String scheduleCourseSql = "DELETE FROM ScheduleCourses WHERE schedule = ?";
                try (var pstmt = db.conn.prepareStatement(scheduleCourseSql)) {
                    pstmt.setInt(1, schedule.getId());
                    pstmt.executeUpdate();
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }

        for (Course course : schedule.getCourses()) {
            try (var pstmt = db.conn.prepareStatement("INSERT INTO ScheduleCourses (schedule, course) VALUES (?, ?)")) {
                pstmt.setInt(1, schedule.getId());
                pstmt.setInt(2, course.getID());
                pstmt.executeUpdate();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }
}
